services:
  nginx:
    image: nginx:1.27.0
    restart: always
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - /srv/docker/face-restoration/logs:/var/log/nginx/
    ports:
        - 10136:80
    depends_on:
        - frontend
        - backend

  backend:
    image: rmrfred/docker-compose-fastapi-vite-nginx-boilerplate-backend:devel
    restart: always
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: docker-compose-fastapi-vite-nginx-boilerplate-backend
    environment:
      API_VERSION: 1.0.0
      API_ENV: "DEV"
      PYTHONPATH: .
    volumes:
      - ./backend/app:/app

  frontend:
    restart: on-failure
    image: rmrfred/docker-compose-fastapi-vite-nginx-boilerplate-frontend:devel
    stdin_open: true
    build: ./frontend
    container_name: docker-compose-fastapi-vite-nginx-boilerplate-frontend
    # command: npm run dev -- --host
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app # Synchronise docker container with local change
      - /app/node_modules # Avoid re-copying local node_modules. Cache in volume. See https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
