services:
  nginx:
    image: nginx:1.27.0
    restart: always
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - /srv/docker/app/logs:/var/log/nginx/
    ports:
        - ${HOST_PORT}:80
    depends_on:
        - frontend
        - backend

  backend:
    image: rmrfred/docker-compose-fastapi-vite-nginx-boilerplate-backend:devel
    restart: always
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: docker-compose-fastapi-vite-nginx-boilerplate-backend
    environment:
      API_VERSION: 1.0.0
      API_ENV: "DEV"
      PYTHONPATH: .
      DEBIAN_FRONTEND: noninteractive
    volumes:
      - ./backend/app:/app

  frontend:
    restart: always
    image: rmrfred/docker-compose-fastapi-vite-nginx-boilerplate-frontend:devel
    build: 
      context: frontend
      dockerfile: Dockerfile
    container_name: docker-compose-fastapi-vite-nginx-boilerplate-frontend
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
