services:
  nginx:
    image: nginx:1.27.0
    restart: always
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - /srv/docker/face-restoration/logs:/var/log/nginx/
    ports:
        - ${HOST_PORT}:80
    depends_on:
        - frontend
        - backend

  backend:
    image: rmrfred/docker-compose-fastapi-vite-nginx-boilerplate-backend:devel
    restart: always
    build: 
      context: backend
      dockerfile: prod.Dockerfile
    container_name: docker-compose-fastapi-vite-nginx-boilerplate-backend
    environment:
      API_VERSION: 1.0.0
      API_ENV: "PROD"
      PYTHONPATH: .
      API_NUM_WORKERS: ${API_NUM_WORKERS}
    volumes:
      - ./backend/app:/app

  frontend:
    restart: on-failure
    image: rmrfred/docker-compose-fastapi-vite-nginx-boilerplate-frontend:devel
    stdin_open: true
    build: 
      context: frontend
      dockerfile: prod.Dockerfile
    container_name: docker-compose-fastapi-vite-nginx-boilerplate-frontend
    environment:
      NODE_ENV: production
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
